# Generated by Django 3.1.1 on 2020-10-25 23:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='users_bookmarked',
            field=models.ManyToManyField(related_name='bookmarked_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
