# Generated by Django 3.1.1 on 2020-09-28 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_remove_event_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='author',
            field=models.CharField(default='no author', max_length=200),
        ),
    ]
