# Generated by Django 3.1.1 on 2020-10-11 18:52

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20201011_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 11, 18, 52, 4, 33397, tzinfo=utc)),
        ),
    ]
