# Generated by Django 3.1.1 on 2020-11-01 05:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0002_event_users_bookmarked'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='atendees',
            field=models.ManyToManyField(related_name='users_attending', to=settings.AUTH_USER_MODEL),
        ),
    ]
