# Generated by Django 3.1.1 on 2020-11-01 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_event_atendees'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='atendees',
            new_name='attendees',
        ),
    ]
