# Generated by Django 3.1.1 on 2020-10-16 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_comment_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='tags',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
