# Generated by Django 3.1.1 on 2020-10-11 18:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auto_20201011_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 11, 18, 55, 55, 153454, tzinfo=utc)),
        ),
    ]
