# Generated by Django 3.1.1 on 2020-10-13 23:41

from django.db import migrations
import django_google_maps.fields


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_auto_20201011_1638'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='address',
            field=django_google_maps.fields.AddressField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='geolocation',
            field=django_google_maps.fields.GeoLocationField(max_length=100, null=True),
        ),
    ]
