# Generated by Django 3.1.1 on 2020-09-28 02:36

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_auto_20200927_2234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 28, 2, 36, 48, 886426, tzinfo=utc)),
        ),
    ]
