# Generated by Django 3.1.1 on 2020-10-02 15:21

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_auto_20200927_2236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 2, 15, 21, 18, 779437, tzinfo=utc)),
        ),
    ]
