# Generated by Django 3.1.1 on 2020-10-05 15:21

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_auto_20201005_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 5, 15, 21, 55, 676557, tzinfo=utc)),
        ),
    ]
