# Generated by Django 3.1.1 on 2020-10-28 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_auto_20201026_1606'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='photo',
            field=models.ImageField(null=True, upload_to='events/images/'),
        ),
        migrations.DeleteModel(
            name='Photo',
        ),
    ]
