# Generated by Django 3.1.1 on 2020-10-04 22:33

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_auto_20201004_1833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 4, 22, 33, 27, 656184, tzinfo=utc)),
        ),
    ]
