# Generated by Django 3.1.1 on 2020-10-02 21:50

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_auto_20201002_1121'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='friends',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 2, 21, 50, 35, 802130, tzinfo=utc)),
        ),
    ]
