# Generated by Django 3.1.1 on 2020-10-05 15:22

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_auto_20201005_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 5, 15, 22, 37, 821742, tzinfo=utc)),
        ),
    ]
