# Generated by Django 3.1.1 on 2020-10-28 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_remove_event_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='photo',
            field=models.ImageField(null=True, upload_to='events/images/'),
        ),
    ]
