# Generated by Django 3.1.1 on 2020-10-02 22:13

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_auto_20201002_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 2, 22, 13, 10, 454342, tzinfo=utc)),
        ),
    ]
