# Generated by Django 3.1.1 on 2020-10-29 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_auto_20201028_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='photo',
            field=models.ImageField(max_length=750, null=True, upload_to='events/images/'),
        ),
    ]
