# Generated by Django 3.1.1 on 2020-10-05 21:13

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_auto_20201005_1646'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='name',
            new_name='tag',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='event',
        ),
        migrations.AlterField(
            model_name='event',
            name='event_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 5, 21, 13, 2, 124019, tzinfo=utc)),
        ),
        migrations.CreateModel(
            name='EvenTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.event')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.tag')),
            ],
        ),
    ]
