# Generated by Django 3.1.1 on 2020-10-05 21:17

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0013_auto_20201005_1713'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EvenTag',
            new_name='EventTag',
        ),
        migrations.AlterField(
            model_name='event',
            name='event_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 5, 21, 17, 16, 782796, tzinfo=utc)),
        ),
    ]
