# Generated by Django 3.1.1 on 2020-10-30 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0013_auto_20201029_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='photo',
            field=models.ImageField(max_length=750, null=True, upload_to='../static/media/images/'),
        ),
    ]
