# Generated by Django 3.1.1 on 2020-10-02 23:07

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0013_auto_20201002_1906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 2, 23, 7, 31, 57324, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='event',
            name='friends',
            field=models.TextField(null=True),
        ),
    ]
