# Generated by Django 3.1.1 on 2020-10-30 02:44

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0014_auto_20201029_2230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='photo',
            field=models.ImageField(max_length=750, null=True, storage=django.core.files.storage.FileSystemStorage(base_url='/images', location='/Users/jonathanmo/Desktop/Jomoswork/CS3240/project-1-25/meet_up_finder/static/media'), upload_to='images'),
        ),
    ]
