# Generated by Django 3.1.1 on 2020-10-30 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0015_auto_20201029_2244'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='photourl',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
