# Generated by Django 3.1.1 on 2020-10-06 02:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0017_auto_20201004_1707'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='users',
            new_name='invitees',
        ),
        migrations.RemoveField(
            model_name='event',
            name='friends',
        ),
        migrations.AlterField(
            model_name='event',
            name='event_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 6, 2, 48, 55, 362988, tzinfo=utc)),
        ),
    ]
