# Generated by Django 3.1.1 on 2020-10-06 03:00

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0018_auto_20201005_2249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 6, 3, 0, 58, 568253, tzinfo=utc)),
        ),
    ]
