# Generated by Django 3.1.1 on 2020-10-07 17:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0019_auto_20201007_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 7, 17, 39, 38, 676389, tzinfo=utc)),
        ),
    ]
