# Generated by Django 3.1.1 on 2020-10-06 03:15

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0019_auto_20201005_2300'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='invitees',
            new_name='users',
        ),
        migrations.AddField(
            model_name='event',
            name='friends',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 6, 3, 15, 27, 902446, tzinfo=utc)),
        ),
    ]
