# Generated by Django 3.1.1 on 2020-10-09 19:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0021_auto_20201009_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 9, 19, 23, 5, 672693, tzinfo=utc)),
        ),
    ]
