# Generated by Django 3.1.1 on 2020-10-06 03:19

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0021_auto_20201005_2319'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='friends',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 6, 3, 19, 57, 586643, tzinfo=utc)),
        ),
    ]
