# Generated by Django 3.1.1 on 2020-10-06 03:25

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0023_auto_20201005_2324'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='friends',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 6, 3, 25, 2, 32485, tzinfo=utc)),
        ),
    ]
