# Generated by Django 3.1.1 on 2020-10-06 17:03

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0025_auto_20201006_0005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 6, 17, 3, 58, 92628, tzinfo=utc)),
        ),
    ]
