# Generated by Django 3.1.1 on 2020-10-11 17:13

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0026_auto_20201006_1303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 11, 17, 13, 58, 567858, tzinfo=utc)),
        ),
    ]
