# Generated by Django 3.1.1 on 2020-10-11 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20201009_1555'),
        ('events', '0026_auto_20201006_1303'),
        ('events', '0022_auto_20201009_1523'),
        ('events', '0013_auto_20201005_0222'),
    ]

    operations = [
    ]
